// C++ implementation of the Blue Robotics 'Ping' binary message protocol

//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
// THIS IS AN AUTOGENERATED FILE
// DO NOT EDIT
//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!

#pragma once

#ifndef S500_ROS2_DRIVER_MESSAGE_PING_MESSAGE_S500_HPP
#define S500_ROS2_DRIVER_MESSAGE_PING_MESSAGE_S500_HPP

#include "s500_ros2_driver/message/ping-message.hpp"

namespace s500_ros2_driver {
namespace message {

// TODO: should maybe be an enum
namespace S500Id
{
    static const uint16_t SET_PING_PARAMS = 1015;
    static const uint16_t SET_SPEED_OF_SOUND = 1002;
    static const uint16_t ALTITUDE = 1211;
    static const uint16_t DISTANCE2 = 1223;
    static const uint16_t FW_VERSION = 1200;
    static const uint16_t GAIN_INDEX = 1207;
    static const uint16_t PING_RATE_MSEC = 1206;
    static const uint16_t PROCESSOR_DEGC = 1213;
    static const uint16_t PROFILE6_T = 1308;
    static const uint16_t RANGE = 1204;
    static const uint16_t SPEED_OF_SOUND = 1203;
}

class s500_set_ping_params : public ping_message
{
public:
    s500_set_ping_params(const ping_message& msg) : ping_message { msg } {}
    s500_set_ping_params(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(30) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(20); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1015; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_set_ping_params(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_set_ping_params() : ping_message { static_cast<uint16_t>(30) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(20); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1015; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t start_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_start_mm(const uint32_t start_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = start_mm; }
    uint32_t length_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_length_mm(const uint32_t length_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = length_mm; }
    int16_t gain_index() const { return reinterpret_cast<int16_t&>(msgData[headerLength + 8]); }
    void set_gain_index(const int16_t gain_index) { reinterpret_cast<int16_t&>(msgData[headerLength + 8]) = gain_index; }
    int16_t msec_per_ping() const { return reinterpret_cast<int16_t&>(msgData[headerLength + 10]); }
    void set_msec_per_ping(const int16_t msec_per_ping) { reinterpret_cast<int16_t&>(msgData[headerLength + 10]) = msec_per_ping; }
    uint16_t pulse_len_usec() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 12]); }
    void set_pulse_len_usec(const uint16_t pulse_len_usec) { reinterpret_cast<uint16_t&>(msgData[headerLength + 12]) = pulse_len_usec; }
    uint16_t report_id() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 14]); }
    void set_report_id(const uint16_t report_id) { reinterpret_cast<uint16_t&>(msgData[headerLength + 14]) = report_id; }
    uint16_t reserved() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 16]); }
    void set_reserved(const uint16_t reserved) { reinterpret_cast<uint16_t&>(msgData[headerLength + 16]) = reserved; }
    uint8_t chirp() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 18]); }
    void set_chirp(const uint8_t chirp) { reinterpret_cast<uint8_t&>(msgData[headerLength + 18]) = chirp; }
    uint8_t decimation() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 19]); }
    void set_decimation(const uint8_t decimation) { reinterpret_cast<uint8_t&>(msgData[headerLength + 19]) = decimation; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  start_mm:  %" PRIu32 "\n"
                "  length_mm:  %" PRIu32 "\n"
                "  gain_index:  %" PRId16 "\n"
                "  msec_per_ping:  %" PRId16 "\n"
                "  pulse_len_usec:  %" PRIu16 "\n"
                "  report_id:  %" PRIu16 "\n"
                "  reserved:  %" PRIu16 "\n"
                "  chirp:  %" PRIu8 "\n"
                "  decimation:  %" PRIu8 "\n"
                , start_mm()
                , length_mm()
                , gain_index()
                , msec_per_ping()
                , pulse_len_usec()
                , report_id()
                , reserved()
                , chirp()
                , decimation()
            );
        }
        return written;
    }
};

class s500_set_speed_of_sound : public ping_message
{
public:
    s500_set_speed_of_sound(const ping_message& msg) : ping_message { msg } {}
    s500_set_speed_of_sound(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1002; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_set_speed_of_sound(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_set_speed_of_sound() : ping_message { static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1002; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t sos_mm_per_sec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_sos_mm_per_sec(const uint32_t sos_mm_per_sec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = sos_mm_per_sec; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  sos_mm_per_sec:  %" PRIu32 "\n"
                , sos_mm_per_sec()
            );
        }
        return written;
    }
};

class s500_altitude : public ping_message
{
public:
    s500_altitude(const ping_message& msg) : ping_message { msg } {}
    s500_altitude(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(15) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(5); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1211; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_altitude(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_altitude() : ping_message { static_cast<uint16_t>(15) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(5); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1211; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t altitude_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_altitude_mm(const uint32_t altitude_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = altitude_mm; }
    uint8_t quality() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 4]); }
    void set_quality(const uint8_t quality) { reinterpret_cast<uint8_t&>(msgData[headerLength + 4]) = quality; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  altitude_mm:  %" PRIu32 "\n"
                "  quality:  %" PRIu8 "\n"
                , altitude_mm()
                , quality()
            );
        }
        return written;
    }
};

class s500_distance2 : public ping_message
{
public:
    s500_distance2(const ping_message& msg) : ping_message { msg } {}
    s500_distance2(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(26) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(16); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1223; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_distance2(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_distance2() : ping_message { static_cast<uint16_t>(26) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(16); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1223; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t ping_distance_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_ping_distance_mm(const uint32_t ping_distance_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = ping_distance_mm; }
    uint32_t averaged_distance_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_averaged_distance_mm(const uint32_t averaged_distance_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = averaged_distance_mm; }
    uint16_t reserved() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 8]); }
    void set_reserved(const uint16_t reserved) { reinterpret_cast<uint16_t&>(msgData[headerLength + 8]) = reserved; }
    uint8_t ping_confidence() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 10]); }
    void set_ping_confidence(const uint8_t ping_confidence) { reinterpret_cast<uint8_t&>(msgData[headerLength + 10]) = ping_confidence; }
    uint8_t average_distance_confidence() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 11]); }
    void set_average_distance_confidence(const uint8_t average_distance_confidence) { reinterpret_cast<uint8_t&>(msgData[headerLength + 11]) = average_distance_confidence; }
    uint32_t timestamp() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 12]); }
    void set_timestamp(const uint32_t timestamp) { reinterpret_cast<uint32_t&>(msgData[headerLength + 12]) = timestamp; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  ping_distance_mm:  %" PRIu32 "\n"
                "  averaged_distance_mm:  %" PRIu32 "\n"
                "  reserved:  %" PRIu16 "\n"
                "  ping_confidence:  %" PRIu8 "\n"
                "  average_distance_confidence:  %" PRIu8 "\n"
                "  timestamp:  %" PRIu32 "\n"
                , ping_distance_mm()
                , averaged_distance_mm()
                , reserved()
                , ping_confidence()
                , average_distance_confidence()
                , timestamp()
            );
        }
        return written;
    }
};

class s500_fw_version : public ping_message
{
public:
    s500_fw_version(const ping_message& msg) : ping_message { msg } {}
    s500_fw_version(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(16) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(6); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1200; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_fw_version(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_fw_version() : ping_message { static_cast<uint16_t>(16) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(6); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1200; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t device_type() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 0]); }
    void set_device_type(const uint8_t device_type) { reinterpret_cast<uint8_t&>(msgData[headerLength + 0]) = device_type; }
    uint8_t device_model() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 1]); }
    void set_device_model(const uint8_t device_model) { reinterpret_cast<uint8_t&>(msgData[headerLength + 1]) = device_model; }
    uint16_t version_major() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 2]); }
    void set_version_major(const uint16_t version_major) { reinterpret_cast<uint16_t&>(msgData[headerLength + 2]) = version_major; }
    uint16_t version_minor() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 4]); }
    void set_version_minor(const uint16_t version_minor) { reinterpret_cast<uint16_t&>(msgData[headerLength + 4]) = version_minor; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  device_type:  %" PRIu8 "\n"
                "  device_model:  %" PRIu8 "\n"
                "  version_major:  %" PRIu16 "\n"
                "  version_minor:  %" PRIu16 "\n"
                , device_type()
                , device_model()
                , version_major()
                , version_minor()
            );
        }
        return written;
    }
};

class s500_gain_index : public ping_message
{
public:
    s500_gain_index(const ping_message& msg) : ping_message { msg } {}
    s500_gain_index(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1207; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_gain_index(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_gain_index() : ping_message { static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1207; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t gain_index() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_gain_index(const uint32_t gain_index) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = gain_index; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  gain_index:  %" PRIu32 "\n"
                , gain_index()
            );
        }
        return written;
    }
};

class s500_ping_rate_msec : public ping_message
{
public:
    s500_ping_rate_msec(const ping_message& msg) : ping_message { msg } {}
    s500_ping_rate_msec(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(12) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(2); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1206; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_ping_rate_msec(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_ping_rate_msec() : ping_message { static_cast<uint16_t>(12) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(2); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1206; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint16_t msec_per_ping() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 0]); }
    void set_msec_per_ping(const uint16_t msec_per_ping) { reinterpret_cast<uint16_t&>(msgData[headerLength + 0]) = msec_per_ping; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  msec_per_ping:  %" PRIu16 "\n"
                , msec_per_ping()
            );
        }
        return written;
    }
};

class s500_processor_degC : public ping_message
{
public:
    s500_processor_degC(const ping_message& msg) : ping_message { msg } {}
    s500_processor_degC(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1213; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_processor_degC(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_processor_degC() : ping_message { static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1213; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t centi_degC() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_centi_degC(const uint32_t centi_degC) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = centi_degC; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  centi_degC:  %" PRIu32 "\n"
                , centi_degC()
            );
        }
        return written;
    }
};

class s500_profile6_t : public ping_message
{
public:
    s500_profile6_t(const ping_message& msg) : ping_message { msg } {}
    s500_profile6_t(uint8_t* buf,
uint16_t pwr_results_length
) : ping_message { buf, static_cast<uint16_t>(78 + pwr_results_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(68 + pwr_results_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1308; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_profile6_t(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_profile6_t(uint16_t pwr_results_length
) : ping_message { static_cast<uint16_t>(78 + pwr_results_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(68 + pwr_results_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1308; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t ping_number() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_ping_number(const uint32_t ping_number) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = ping_number; }
    uint32_t start_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_start_mm(const uint32_t start_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = start_mm; }
    uint32_t length_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 8]); }
    void set_length_mm(const uint32_t length_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 8]) = length_mm; }
    uint32_t start_ping_hz() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 12]); }
    void set_start_ping_hz(const uint32_t start_ping_hz) { reinterpret_cast<uint32_t&>(msgData[headerLength + 12]) = start_ping_hz; }
    uint32_t end_ping_hz() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 16]); }
    void set_end_ping_hz(const uint32_t end_ping_hz) { reinterpret_cast<uint32_t&>(msgData[headerLength + 16]) = end_ping_hz; }
    uint32_t adc_sample_hz() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 20]); }
    void set_adc_sample_hz(const uint32_t adc_sample_hz) { reinterpret_cast<uint32_t&>(msgData[headerLength + 20]) = adc_sample_hz; }
    uint32_t timestamp_msec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 24]); }
    void set_timestamp_msec(const uint32_t timestamp_msec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 24]) = timestamp_msec; }
    uint32_t spare2() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 28]); }
    void set_spare2(const uint32_t spare2) { reinterpret_cast<uint32_t&>(msgData[headerLength + 28]) = spare2; }
    float pulse_duration_sec() const { return reinterpret_cast<float&>(msgData[headerLength + 32]); }
    void set_pulse_duration_sec(const float pulse_duration_sec) { reinterpret_cast<float&>(msgData[headerLength + 32]) = pulse_duration_sec; }
    float analog_gain() const { return reinterpret_cast<float&>(msgData[headerLength + 36]); }
    void set_analog_gain(const float analog_gain) { reinterpret_cast<float&>(msgData[headerLength + 36]) = analog_gain; }
    float max_pwr_db() const { return reinterpret_cast<float&>(msgData[headerLength + 40]); }
    void set_max_pwr_db(const float max_pwr_db) { reinterpret_cast<float&>(msgData[headerLength + 40]) = max_pwr_db; }
    float min_pwr_db() const { return reinterpret_cast<float&>(msgData[headerLength + 44]); }
    void set_min_pwr_db(const float min_pwr_db) { reinterpret_cast<float&>(msgData[headerLength + 44]) = min_pwr_db; }
    float this_ping_depth_m() const { return reinterpret_cast<float&>(msgData[headerLength + 48]); }
    void set_this_ping_depth_m(const float this_ping_depth_m) { reinterpret_cast<float&>(msgData[headerLength + 48]) = this_ping_depth_m; }
    float smooth_depth_m() const { return reinterpret_cast<float&>(msgData[headerLength + 52]); }
    void set_smooth_depth_m(const float smooth_depth_m) { reinterpret_cast<float&>(msgData[headerLength + 52]) = smooth_depth_m; }
    float fspare2() const { return reinterpret_cast<float&>(msgData[headerLength + 56]); }
    void set_fspare2(const float fspare2) { reinterpret_cast<float&>(msgData[headerLength + 56]) = fspare2; }
    uint8_t ping_depth_measurement_confidence() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 60]); }
    void set_ping_depth_measurement_confidence(const uint8_t ping_depth_measurement_confidence) { reinterpret_cast<uint8_t&>(msgData[headerLength + 60]) = ping_depth_measurement_confidence; }
    uint8_t gain_index() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 61]); }
    void set_gain_index(const uint8_t gain_index) { reinterpret_cast<uint8_t&>(msgData[headerLength + 61]) = gain_index; }
    uint8_t decimation() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 62]); }
    void set_decimation(const uint8_t decimation) { reinterpret_cast<uint8_t&>(msgData[headerLength + 62]) = decimation; }
    uint8_t smoothed_depth_measurement_confidence() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 63]); }
    void set_smoothed_depth_measurement_confidence(const uint8_t smoothed_depth_measurement_confidence) { reinterpret_cast<uint8_t&>(msgData[headerLength + 63]) = smoothed_depth_measurement_confidence; }
    uint16_t num_results() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 64]); }
    void set_num_results(const uint16_t num_results) { reinterpret_cast<uint16_t&>(msgData[headerLength + 64]) = num_results; }
    uint16_t pwr_results_length() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 66]); }
    //TODO do this in constructor (const)
    void set_pwr_results_length(const uint16_t pwr_results_length) { reinterpret_cast<uint16_t&>(msgData[headerLength + 66]) = pwr_results_length;}
    uint16_t* pwr_results() const { return reinterpret_cast<uint16_t*>(msgData+headerLength+68); }
    void set_pwr_results_at(const uint16_t i, const uint16_t data) { reinterpret_cast<uint16_t&>(msgData[headerLength + 68 + i]) = data; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  ping_number:  %" PRIu32 "\n"
                "  start_mm:  %" PRIu32 "\n"
                "  length_mm:  %" PRIu32 "\n"
                "  start_ping_hz:  %" PRIu32 "\n"
                "  end_ping_hz:  %" PRIu32 "\n"
                "  adc_sample_hz:  %" PRIu32 "\n"
                "  timestamp_msec:  %" PRIu32 "\n"
                "  spare2:  %" PRIu32 "\n"
                "  pulse_duration_sec:  %f\n"
                "  analog_gain:  %f\n"
                "  max_pwr_db:  %f\n"
                "  min_pwr_db:  %f\n"
                "  this_ping_depth_m:  %f\n"
                "  smooth_depth_m:  %f\n"
                "  fspare2:  %f\n"
                "  ping_depth_measurement_confidence:  %" PRIu8 "\n"
                "  gain_index:  %" PRIu8 "\n"
                "  decimation:  %" PRIu8 "\n"
                "  smoothed_depth_measurement_confidence:  %" PRIu8 "\n"
                "  num_results:  %" PRIu16 "\n"
                , ping_number()
                , start_mm()
                , length_mm()
                , start_ping_hz()
                , end_ping_hz()
                , adc_sample_hz()
                , timestamp_msec()
                , spare2()
                , pulse_duration_sec()
                , analog_gain()
                , max_pwr_db()
                , min_pwr_db()
                , this_ping_depth_m()
                , smooth_depth_m()
                , fspare2()
                , ping_depth_measurement_confidence()
                , gain_index()
                , decimation()
                , smoothed_depth_measurement_confidence()
                , num_results()
            );
        }
        return written;
    }
};

class s500_range : public ping_message
{
public:
    s500_range(const ping_message& msg) : ping_message { msg } {}
    s500_range(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(18) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(8); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1204; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_range(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_range() : ping_message { static_cast<uint16_t>(18) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(8); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1204; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t start_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_start_mm(const uint32_t start_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = start_mm; }
    uint32_t length_mm() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_length_mm(const uint32_t length_mm) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = length_mm; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  start_mm:  %" PRIu32 "\n"
                "  length_mm:  %" PRIu32 "\n"
                , start_mm()
                , length_mm()
            );
        }
        return written;
    }
};

class s500_speed_of_sound : public ping_message
{
public:
    s500_speed_of_sound(const ping_message& msg) : ping_message { msg } {}
    s500_speed_of_sound(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1203; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    s500_speed_of_sound(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    s500_speed_of_sound() : ping_message { static_cast<uint16_t>(14) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(4); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 1203; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t sos_mm_per_sec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_sos_mm_per_sec(const uint32_t sos_mm_per_sec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = sos_mm_per_sec; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  sos_mm_per_sec:  %" PRIu32 "\n"
                , sos_mm_per_sec()
            );
        }
        return written;
    }
};

} // namespace message
} // namespace s500_ros2_driver

#endif // S500_ROS2_DRIVER_MESSAGE_PING_MESSAGE_S500_HPP
