/*
 * A device API for the s500
 *
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT EDIT
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 *
 */

#pragma once

#ifndef S500_ROS2_DRIVER_DEVICE_PING_DEVICE_S500_HPP
#define S500_ROS2_DRIVER_DEVICE_PING_DEVICE_S500_HPP

#include "s500_ros2_driver/device/ping-device.hpp"

namespace s500_ros2_driver {
namespace device {

class S500 : public PingDevice
{
public:
    /**
     *  @brief Constructor
     *
     *  @param ser: The device I/O
     */
    S500(PingPort& port) : PingDevice(port) {}

    /**
     * @brief Destructor
     */
    ~S500();

    /**
     *  @brief Establish communications with the device, and initialize the update interval
     *  @return true if the device was initialized successfully
     */
    bool initialize();

// This loop is the critical part. It must iterate over "control" for s500.json.
    /**
     * @brief Set parameters
     *
     * @param start_mm - Units: mm; Start of ping range, normally set to 0.
     * @param length_mm - Units: mm; Length of the returned profile. End of range = start_mm + length_mm. Set to 0 for auto_range.
     * @param gain_index - Set to -1 for auto gain, otherwise 0-13 sets gain for manual gain.
     * @param msec_per_ping - Units: msec; Set to -1 to start a single ping. Otherwise sets minimum ping interval.
     * @param pulse_len_usec - 0 for auto mode. Currently ignored and auto duration is always used.
     * @param report_id - The ID of the packet type that you would like in response. Options are distance2 (1223), profile6 (1308), or zero. Zero disables pinging.
     * @param reserved - Set to 0
     * @param chirp - Set to 1 for chirp, 0 for monotone ping.
     * @param decimation - Set to 0 for auto range resolution in chirp mode
     *
     * @return when verify = false: true if a valid reply is received from the device.
     * @return when verify = true: true if a valid reply is received from the
     * device, and the values in the reply match the values that we applied
     */
    bool set_ping_params(uint32_t start_mm, uint32_t length_mm, int16_t gain_index, int16_t msec_per_ping, uint16_t pulse_len_usec, uint16_t report_id, uint16_t reserved, uint8_t chirp, uint8_t decimation, bool verify = true);

    /**
     * @brief Set the speed of sound
     *
     * @param sos_mm_per_sec - Units: mm/s; The speed of sound in the measurement medium, ~1,500,000 mm/s for water.
     *
     * @return when verify = false: true if a valid reply is received from the device.
     * @return when verify = true: true if a valid reply is received from the
     * device, and the values in the reply match the values that we applied
     */
    bool set_speed_of_sound(uint32_t sos_mm_per_sec, bool verify = true);


    //! 
    struct {
        // Result of most recent calculated distance from device to bottom (or other target).
        uint32_t altitude_mm;
        // Measure of confidence of altitude measure, 0 (No idea) to 100 (Quite sure).
        uint8_t quality;
    } altitude_data;

    //! Reports a simple distance measurement.
    struct {
        // Distance of most recent ping
        uint32_t ping_distance_mm;
        // Average distance over last 20 pings
        uint32_t averaged_distance_mm;
        // 
        uint16_t reserved;
        // 0 to 100
        uint8_t ping_confidence;
        // 0 to 100
        uint8_t average_distance_confidence;
        // 
        uint32_t timestamp;
    } distance2_data;

    //! 
    struct {
        // 
        uint8_t device_type;
        // 
        uint8_t device_model;
        // 
        uint16_t version_major;
        // 
        uint16_t version_minor;
    } fw_version_data;

    //! 
    struct {
        // Current gain index setting
        uint32_t gain_index;
    } gain_index_data;

    //! 
    struct {
        // Minimum time between successive pings. Can be longer depending on range.
        uint16_t msec_per_ping;
    } ping_rate_msec_data;

    //! 
    struct {
        // Device CPU temperature, result = degrees C * 100
        uint32_t centi_degC;
    } processor_degC_data;

    //! Reports a measure of signal strength at all depths within the ping range. This could be used to present a 'waterfall' type display similar to a commercial marine depth sounder or fish finder. The Cerulean SonarView app uses profile6_t to do just that. The native number of results reported for the profile6_t is 1024 for monotone pings. For chirp pings, the range resolution is affected by the 'decimation' field in the set_ping_params command. If decimation is set to 0, the device will vary decimation depending on range. The smallest decimation will be used that does not exceed 6000 reported data elements. Keep in mind the bandwidth of the communication channel in use when considering which profile report to use. For example, profile6_t can generate a lot of data, and is probably best used with the USB or Ethernet interface.
    struct {
        // Sequentially assigned from 0 at power up.
        uint32_t ping_number;
        // Start of ping range
        uint32_t start_mm;
        // Length of the returned profile. End of range = start_mm + length_mm.
        uint32_t length_mm;
        // Initial frequency of ping.
        uint32_t start_ping_hz;
        // Final frequency of ping.
        uint32_t end_ping_hz;
        // Sampling rate of adc
        uint32_t adc_sample_hz;
        // 
        uint32_t timestamp_msec;
        // 
        uint32_t spare2;
        // Pulse duration in seconds.
        float pulse_duration_sec;
        // 
        float analog_gain;
        // Maximum power level in dB.
        float max_pwr_db;
        // Minimum power level in dB.
        float min_pwr_db;
        // Depth in meters as calculated from most recent ping.
        float this_ping_depth_m;
        // Smoothed calculated depth in meters.
        float smooth_depth_m;
        // 0
        float fspare2;
        // Depth measurement confidence (0-100) based on most recent ping.
        uint8_t ping_depth_measurement_confidence;
        // 
        uint8_t gain_index;
        // 
        uint8_t decimation;
        // 0 (0-100)
        uint8_t smoothed_depth_measurement_confidence;
        // 
        uint16_t num_results;
        // Power results scaled from min_pwr to max_pwr. num_results entries.
        uint16_t* pwr_results = nullptr;
        uint16_t pwr_results_length = 0;
    } profile6_t_data;

    //! 
    struct {
        // Normally 0.
        uint32_t start_mm;
        // start_mm + length_mm is max range.
        uint32_t length_mm;
    } range_data;

    //! 
    struct {
        // Current speed of sound setting in mm/sec, default is 1500 m/sec.
        uint32_t sos_mm_per_sec;
    } speed_of_sound_data;


private:
    /**
     *  @brief Handle an incoming message from the device. Internal values are updated according to the device data.
     *
     *  @param message: A pointer to the message received from the device
     */
    void _handleMessage(const ping_message* message) override;
};

} // namespace device
} // namespace s500_ros2_driver

#endif // S500_ROS2_DRIVER_DEVICE_PING_DEVICE_S500_HPP
